name: validate-pr

on:
  pull_request:
    types: [opened, reopened, edited]
    # only applies to PRs that intent to be released to the public
    branches:
      - main
      - release-base/**

jobs:
  validate-pr:
    uses: salesforcecli/github-workflows/.github/workflows/validatePR.yml@main
